### ISSUE TITLE
Edit a todo - `EditViewModel`

### ISSUE THREAD

**Issue by gentledepp** [eszterhorvath/ToDo#5]
- [x] implement an `EditViewModel` which allows the user to edit an existing todo. (Maybe (s)he mistyped the description ;-))
- [x] use the `IMvxNavigationService` to properly navigate to it once an item in the list is *selected*
  - [x] pass the id of the todo item that should be edited as a parameter (`EditViewModel.Prepare()`)
  - [ ] load the todo item in the `EditViewModel.Initialize()` method - asynchronously

- [x] write a unit test that verifies the interaction of the `TodoViewModel` and the `EditViewModel`!

**Comment by gentledepp** [comment]
@b

**Comment by eszterhorvath** [comment]
I added EditViewModel: #11
